language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc

addons:
  apt:
    packages:
      - libsdl1.2-dev 
      - libgtk2.0-dev

script:
  - cd BasiliskII/src/Unix
  - NO_CONFIGURE=1 ./autogen.sh
  - ./configure --prefix=/usr --enable-sdl-video --enable-sdl-audio --disable-vosf --disable-jit-compiler --with-x --with-gtk --with-mon
  - make -j$(nproc)
  # The following should be hosted inside this repository rather than grabbed from somewhere
  - mkdir -p appdir/usr/share/applications/ ; wget "https://raw.githubusercontent.com/rpmfusion/BasiliskII/master/BasiliskII.desktop" -O appdir/usr/share/applications/BasiliskII.desktop
  - mkdir -p appdir/usr/share/icons/hicolor/128x128/apps ; wget "https://github.com/rpmfusion/BasiliskII/raw/master/BasiliskII.png" -O appdir/usr/share/icons/hicolor/128x128/apps/BasiliskII.png
  - mkdir -p appdir/usr/share/appdata/ ; wget "https://raw.githubusercontent.com/rpmfusion/BasiliskII/master/BasiliskII.appdata.xml" -O appdir/usr/share/appdata/BasiliskII.appdata.xml
  - make install DESTDIR=$(readlink -f appdir) ; find appdir/
  - cd appdir
  - find usr/ -type f -exec sed -i -e 's|/usr|././|g' {} \; # Patch away absolute paths; it would be nice if they were relative
  - find usr/ -type f -exec sed -i -e 's@././/bin/env@/usr/bin/env@g' {} \; # Patch away absolute paths; it would be nice if they were relative
  - cd ..
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh Basilisk_II*.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
